"""
扩展财务因子库 - 从21个扩展到100个

覆盖: 盈利能力、成长能力、估值、运营效率、杠杆、现金流、质量等七大类
"""

from dataclasses import dataclass


@dataclass
class ExtendedFinancialFactor:
    """扩展财务因子定义"""
    name: str
    category: str
    sub_category: str
    description: str
    economic_interpretation: str
    lookback: int
    data_requirement: list[str]
    computation: str
    ic_direction: str  # positive, negative, conditional
    paper_reference: str | None = None


# ===== 扩展财务因子池 (100个) =====

EXTENDED_FINANCIAL_FACTORS: list[ExtendedFinancialFactor] = [

    # ========== 一、盈利能力类 (20个) ==========

    # ROE及其变体
    ExtendedFinancialFactor(
        name="roe_ttm",
        category="profitability",
        sub_category="roe_variants",
        description="滚动12个月ROE",
        economic_interpretation="净利润/股东权益，反映股东回报率",
        lookback=0,
        data_requirement=["net_profit", "total_equity"],
        computation="net_profit_ttm / total_equity",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roe_qoq",
        category="profitability",
        sub_category="roe_variants",
        description="ROE季度环比变化",
        economic_interpretation="ROE改善趋势",
        lookback=0,
        data_requirement=["roe"],
        computation="roe_q / roe_q-1 - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roe_yoy",
        category="profitability",
        sub_category="roe_variants",
        description="ROE同比变化",
        economic_interpretation="ROE同比改善",
        lookback=0,
        data_requirement=["roe"],
        computation="roe_q / roe_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roe_stability",
        category="profitability",
        sub_category="roe_variants",
        description="ROE稳定性 (过去8季度标准差倒数)",
        economic_interpretation="ROE波动小=盈利稳定",
        lookback=500,
        data_requirement=["roe"],
        computation="1 / std(roe_last_8q)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roe_weighted_3y",
        category="profitability",
        sub_category="roe_variants",
        description="三年加权ROE (近重远轻)",
        economic_interpretation="持续盈利能力",
        lookback=750,
        data_requirement=["roe"],
        computation="sum(roe * [0.5,0.3,0.2]) / sum([0.5,0.3,0.2])",
        ic_direction="positive",
    ),

    # ROA及其变体
    ExtendedFinancialFactor(
        name="roa_ttm",
        category="profitability",
        sub_category="roa_variants",
        description="滚动12个月ROA",
        economic_interpretation="总资产回报率",
        lookback=0,
        data_requirement=["net_profit", "total_assets"],
        computation="net_profit_ttm / total_assets",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roa_qoq",
        category="profitability",
        sub_category="roa_variants",
        description="ROA季度环比变化",
        economic_interpretation="资产使用效率改善",
        lookback=0,
        data_requirement=["roa"],
        computation="roa_q / roa_q-1 - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roce",
        category="profitability",
        sub_category="roa_variants",
        description="投入资本回报率",
        economic_interpretation="使用投入资本的回报效率",
        lookback=0,
        data_requirement=["ebit", "total_assets", "current_liabilities"],
        computation="EBIT / (total_assets - current_liabilities)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roic",
        category="profitability",
        sub_category="roa_variants",
        description="投资资本回报率",
        economic_interpretation="使用投资资本的回报效率",
        lookback=0,
        data_requirement=["nopat", "invested_capital"],
        computation="NOPAT / invested_capital",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="roe_excellent",
        category="profitability",
        sub_category="roe_variants",
        description="ROE是否优秀 (>15%)",
        economic_interpretation="高ROE公司",
        lookback=0,
        data_requirement=["roe"],
        computation="roe > 0.15",
        ic_direction="positive",
    ),

    # 利润率因子
    ExtendedFinancialFactor(
        name="gross_margin_ttm",
        category="profitability",
        sub_category="margin_factors",
        description="滚动毛利率",
        economic_interpretation="主营业务盈利能力",
        lookback=0,
        data_requirement=["revenue", "cost"],
        computation="(revenue - cost) / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="operating_margin_ttm",
        category="profitability",
        sub_category="margin_factors",
        description="滚动营业利润率",
        economic_interpretation="营业活动盈利能力",
        lookback=0,
        data_requirement=["operating_profit", "revenue"],
        computation="operating_profit / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="net_margin_ttm",
        category="profitability",
        sub_category="margin_factors",
        description="滚动净利率",
        economic_interpretation="最终盈利能力",
        lookback=0,
        data_requirement=["net_profit", "revenue"],
        computation="net_profit / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="ebit_margin",
        category="profitability",
        sub_category="margin_factors",
        description="EBIT利润率",
        economic_interpretation="息税前盈利能力",
        lookback=0,
        data_requirement=["ebit", "revenue"],
        computation="EBIT / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="ebitda_margin",
        category="profitability",
        sub_category="margin_factors",
        description="EBITDA利润率",
        economic_interpretation="含折旧摊销的盈利",
        lookback=0,
        data_requirement=["ebitda", "revenue"],
        computation="EBITDA / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="pre_tax_margin",
        category="profitability",
        sub_category="margin_factors",
        description="税前利润率",
        economic_interpretation="税前盈利能力",
        lookback=0,
        data_requirement=["profit_before_tax", "revenue"],
        computation="profit_before_tax / revenue",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="margin_expansion",
        category="profitability",
        sub_category="margin_factors",
        description="毛利率扩张 (当前-历史平均)",
        economic_interpretation="定价能力提升",
        lookback=250,
        data_requirement=["gross_margin"],
        computation="gross_margin - mean(gross_margin_last_2y)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="margin_cv",
        category="profitability",
        sub_category="margin_factors",
        description="毛利率变异系数",
        economic_interpretation="盈利稳定性(越小越好)",
        lookback=500,
        data_requirement=["gross_margin"],
        computation="std(gross_margin) / mean(gross_margin)",
        ic_direction="negative",
    ),

    # 其他盈利能力
    ExtendedFinancialFactor(
        name="cash_roe",
        category="profitability",
        sub_category="cash_factors",
        description="现金ROE (经营现金流/股东权益)",
        economic_interpretation="真金白银的股东回报",
        lookback=0,
        data_requirement=["operating_cash_flow", "total_equity"],
        computation="operating_cash_flow / total_equity",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="asset_turnover_ttm",
        category="profitability",
        sub_category="turnover_factors",
        description="滚动资产周转率",
        economic_interpretation="资产使用效率",
        lookback=0,
        data_requirement=["revenue", "total_assets"],
        computation="revenue_ttm / avg(total_assets)",
        ic_direction="positive",
    ),

    # ========== 二、成长能力类 (15个) ==========

    ExtendedFinancialFactor(
        name="revenue_growth_qoq",
        category="growth",
        sub_category="revenue_growth",
        description="营收季度环比增速",
        economic_interpretation="营收增长动能",
        lookback=0,
        data_requirement=["revenue"],
        computation="revenue_q / revenue_q-1 - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="revenue_growth_yoy_ttm",
        category="growth",
        sub_category="revenue_growth",
        description="滚动营收同比增速",
        economic_interpretation="营收持续增长能力",
        lookback=0,
        data_requirement=["revenue"],
        computation="revenue_ttm / revenue_ttm_4q_ago - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="revenue_cagr_3y",
        category="growth",
        sub_category="revenue_growth",
        description="营收三年CAGR",
        economic_interpretation="长期成长能力",
        lookback=750,
        data_requirement=["revenue"],
        computation="(revenue_current / revenue_3y_ago)^(1/3) - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="profit_growth_qoq",
        category="growth",
        sub_category="profit_growth",
        description="净利润季度环比增速",
        economic_interpretation="利润增长动能",
        lookback=0,
        data_requirement=["net_profit"],
        computation="net_profit_q / net_profit_q-1 - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="profit_growth_yoy_ttm",
        category="growth",
        sub_category="profit_growth",
        description="滚动净利润同比增速",
        economic_interpretation="利润持续增长能力",
        lookback=0,
        data_requirement=["net_profit"],
        computation="net_profit_ttm / net_profit_ttm_4q_ago - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="profit_cagr_3y",
        category="growth",
        sub_category="profit_growth",
        description="净利润三年CAGR",
        economic_interpretation="长期盈利能力",
        lookback=750,
        data_requirement=["net_profit"],
        computation="(net_profit_current / net_profit_3y_ago)^(1/3) - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="operating_profit_growth_yoy",
        category="growth",
        sub_category="profit_growth",
        description="营业利润同比增速",
        economic_interpretation="主营业务增长",
        lookback=0,
        data_requirement=["operating_profit"],
        computation="operating_profit / operating_profit_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="ebit_growth_yoy",
        category="growth",
        sub_category="profit_growth",
        description="EBIT同比增速",
        economic_interpretation="息税前利润增长",
        lookback=0,
        data_requirement=["ebit"],
        computation="ebit / ebit_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="ocf_growth_yoy",
        category="growth",
        sub_category="cash_growth",
        description="经营现金流同比增速",
        economic_interpretation="现金流增长",
        lookback=0,
        data_requirement=["operating_cash_flow"],
        computation="ocf / ocf_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="asset_growth_yoy",
        category="growth",
        sub_category="asset_growth",
        description="总资产同比增速",
        economic_interpretation="资产扩张速度",
        lookback=0,
        data_requirement=["total_assets"],
        computation="total_assets / total_assets_same_q_last_year - 1",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="equity_growth_yoy",
        category="growth",
        sub_category="equity_growth",
        description="净资产同比增速",
        economic_interpretation="内生增长能力",
        lookback=0,
        data_requirement=["total_equity"],
        computation="total_equity / total_equity_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="bvps_growth_yoy",
        category="growth",
        sub_category="bvps_growth",
        description="每股净资产同比增速",
        economic_interpretation="股东价值增长",
        lookback=0,
        data_requirement=["bvps"],
        computation="bvps / bvps_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="eps_growth_yoy",
        category="growth",
        sub_category="eps_growth",
        description="EPS同比增速",
        economic_interpretation="每股盈利增长",
        lookback=0,
        data_requirement=["eps"],
        computation="eps / eps_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="revenue_acceleration",
        category="growth",
        sub_category="acceleration",
        description="营收增长加速度",
        economic_interpretation="增长是否加速",
        lookback=0,
        data_requirement=["revenue"],
        computation="revenue_growth_yoy - revenue_growth_yoy_1q_ago",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="profit_acceleration",
        category="growth",
        sub_category="acceleration",
        description="利润增长加速度",
        economic_interpretation="盈利增长是否加速",
        lookback=0,
        data_requirement=["net_profit"],
        computation="profit_growth_yoy - profit_growth_yoy_1q_ago",
        ic_direction="positive",
    ),

    # ========== 三、估值因子类 (20个) ==========

    ExtendedFinancialFactor(
        name="pe_ttm",
        category="valuation",
        sub_category="pe_ratios",
        description="滚动市盈率",
        economic_interpretation="价格/盈利，估值水平",
        lookback=0,
        data_requirement=["price", "eps_ttm"],
        computation="price / eps_ttm",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="pe_forward",
        category="valuation",
        sub_category="pe_ratios",
        description="前瞻市盈率",
        economic_interpretation="预期估值",
        lookback=0,
        data_requirement=["price", "eps_forward"],
        computation="price / eps_forward",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="pe_g",
        category="valuation",
        sub_category="pe_ratios",
        description="PEG (动态市盈率/增速)",
        economic_interpretation="成长调整后估值",
        lookback=0,
        data_requirement=["pe_ttm", "profit_growth_yoy"],
        computation="pe_ttm / profit_growth_yoy * 100",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="pe_historical_low",
        category="valuation",
        sub_category="pe_ratios",
        description="PE历史分位 (当前/5年低点)",
        economic_interpretation="相对历史估值",
        lookback=1250,
        data_requirement=["pe_ttm"],
        computation="percentile_rank(pe_ttm, 5y)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="pb",
        category="valuation",
        sub_category="pb_ratios",
        description="市净率",
        economic_interpretation="价格/净资产",
        lookback=0,
        data_requirement=["price", "book_value_per_share"],
        computation="price / book_value_per_share",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="pb_median",
        category="valuation",
        sub_category="pb_ratios",
        description="PB相对行业中位数",
        economic_interpretation="相对行业估值",
        lookback=0,
        data_requirement=["pb", "industry_pb"],
        computation="pb / industry_median_pb",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="ps",
        category="valuation",
        sub_category="ps_ratios",
        description="市销率",
        economic_interpretation="价格/销售额",
        lookback=0,
        data_requirement=["price", "revenue_per_share"],
        computation="price / revenue_per_share",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="pcf",
        category="valuation",
        sub_category="pcf_ratios",
        description="市现率 (P/CF)",
        economic_interpretation="价格/现金流",
        lookback=0,
        data_requirement=["price", "cash_flow_per_share"],
        computation="price / cash_flow_per_share",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="ev_ebitda",
        category="valuation",
        sub_category="ev_ratios",
        description="EV/EBITDA",
        economic_interpretation="企业价值倍数",
        lookback=0,
        data_requirement=["market_cap", "net_debt", "ebitda"],
        computation="(market_cap + net_debt) / ebitda",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="ev_sales",
        category="valuation",
        sub_category="ev_ratios",
        description="EV/销售额",
        economic_interpretation="企业价值相对销售",
        lookback=0,
        data_requirement=["market_cap", "net_debt", "revenue"],
        computation="(market_cap + net_debt) / revenue",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="ev_ebit",
        category="valuation",
        sub_category="ev_ratios",
        description="EV/EBIT",
        economic_interpretation="企业价值倍数",
        lookback=0,
        data_requirement=["market_cap", "net_debt", "ebit"],
        computation="(market_cap + net_debt) / ebit",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="dividend_yield",
        category="valuation",
        sub_category="dividend_factors",
        description="股息率",
        economic_interpretation="现金回报率",
        lookback=0,
        data_requirement=["dividend_per_share", "price"],
        computation="dividend_per_share / price",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="payout_ratio",
        category="valuation",
        sub_category="dividend_factors",
        description="分红率",
        economic_interpretation="利润分配比例",
        lookback=0,
        data_requirement=["dividend_per_share", "eps"],
        computation="dividend_per_share / eps",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="earnings_yield",
        category="valuation",
        sub_category="earnings_yield",
        description="盈利收益率 (1/PE)",
        economic_interpretation="盈利相对价格",
        lookback=0,
        data_requirement=["eps", "price"],
        computation="eps / price",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="cf_yield",
        category="valuation",
        sub_category="cash_yield",
        description="现金流收益率",
        economic_interpretation="现金流相对价格",
        lookback=0,
        data_requirement=["ocf_per_share", "price"],
        computation="ocf_per_share / price",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="book_yield",
        category="valuation",
        sub_category="book_yield",
        description="净资产收益率",
        economic_interpretation="净资产相对价格",
        lookback=0,
        data_requirement=["bvps", "price"],
        computation="bvps / price",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="revenue_ocf_ratio",
        category="valuation",
        sub_category="quality_metrics",
        description="营收/经营现金流",
        economic_interpretation="收入质量",
        lookback=0,
        data_requirement=["revenue", "operating_cash_flow"],
        computation="revenue / operating_cash_flow",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="pe_5y_avg",
        category="valuation",
        sub_category="pe_ratios",
        description="PE相对5年平均",
        economic_interpretation="估值历史位置",
        lookback=1250,
        data_requirement=["pe_ttm"],
        computation="pe_ttm / mean(pe_ttm_last_5y)",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="pb_5y_avg",
        category="valuation",
        sub_category="pb_ratios",
        description="PB相对5年平均",
        economic_interpretation="估值历史位置",
        lookback=1250,
        data_requirement=["pb"],
        computation="pb / mean(pb_last_5y)",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="ev_ebitda_industry_adj",
        category="valuation",
        sub_category="ev_ratios",
        description="EV/EBITDA行业调整",
        economic_interpretation="相对行业估值",
        lookback=0,
        data_requirement=["ev_ebitda", "industry_ev_ebitda"],
        computation="ev_ebitda / industry_median",
        ic_direction="negative",
    ),

    # ========== 四、运营效率类 (10个) ==========

    ExtendedFinancialFactor(
        name="asset_turnover",
        category="efficiency",
        sub_category="asset_turnover",
        description="资产周转率",
        economic_interpretation="资产使用效率",
        lookback=0,
        data_requirement=["revenue", "total_assets"],
        computation="revenue / avg(total_assets)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="inventory_turnover",
        category="efficiency",
        sub_category="inventory_turnover",
        description="存货周转率",
        economic_interpretation="存货管理效率",
        lookback=0,
        data_requirement=["cost_of_goods_sold", "inventory"],
        computation="cogs / avg(inventory)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="receivable_turnover",
        category="efficiency",
        sub_category="receivable_turnover",
        description="应收账款周转率",
        economic_interpretation="应收账款管理",
        lookback=0,
        data_requirement=["revenue", "accounts_receivable"],
        computation="revenue / avg(accounts_receivable)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="payable_turnover",
        category="efficiency",
        sub_category="payable_turnover",
        description="应付账款周转率",
        economic_interpretation="供应商管理",
        lookback=0,
        data_requirement=["cost_of_goods_sold", "accounts_payable"],
        computation="cogs / avg(accounts_payable)",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="cash_turnover",
        category="efficiency",
        sub_category="cash_turnover",
        description="现金周转率",
        economic_interpretation="现金使用效率",
        lookback=0,
        data_requirement=["revenue", "cash"],
        computation="revenue / avg(cash)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="working_capital_turnover",
        category="efficiency",
        sub_category="wc_turnover",
        description="营运资本周转率",
        economic_interpretation="营运资本效率",
        lookback=0,
        data_requirement=["revenue", "working_capital"],
        computation="revenue / avg(working_capital)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="equity_turnover",
        category="efficiency",
        sub_category="equity_turnover",
        description="净资产周转率",
        economic_interpretation="净资产使用效率",
        lookback=0,
        data_requirement=["revenue", "total_equity"],
        computation="revenue / avg(total_equity)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="fixed_asset_turnover",
        category="efficiency",
        sub_category="fixed_asset_turnover",
        description="固定资产周转率",
        economic_interpretation="固定资产效率",
        lookback=0,
        data_requirement=["revenue", "fixed_assets"],
        computation="revenue / avg(fixed_assets)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="operating_cycle",
        category="efficiency",
        sub_category="cycle_metrics",
        description="营业周期 (天)",
        economic_interpretation="从采购到收款天数",
        lookback=0,
        data_requirement=["inventory", "receivable"],
        computation="inventory_days + receivable_days",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="cash_cycle",
        category="efficiency",
        sub_category="cycle_metrics",
        description="现金周期 (天)",
        economic_interpretation="实际占用现金天数",
        lookback=0,
        data_requirement=["inventory", "receivable", "payable"],
        computation="inventory_days + receivable_days - payable_days",
        ic_direction="negative",
    ),

    # ========== 五、杠杆/偿债类 (12个) ==========

    ExtendedFinancialFactor(
        name="debt_ratio",
        category="leverage",
        sub_category="debt_ratios",
        description="资产负债率",
        economic_interpretation="总负债/总资产",
        lookback=0,
        data_requirement=["total_liabilities", "total_assets"],
        computation="total_liabilities / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="debt_to_equity",
        category="leverage",
        sub_category="debt_ratios",
        description="产权比率",
        economic_interpretation="负债/权益",
        lookback=0,
        data_requirement=["total_liabilities", "total_equity"],
        computation="total_liabilities / total_equity",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="long_term_debt_ratio",
        category="leverage",
        sub_category="debt_ratios",
        description="长期负债率",
        economic_interpretation="长期负债占比",
        lookback=0,
        data_requirement=["long_term_debt", "total_assets"],
        computation="long_term_debt / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="current_ratio",
        category="leverage",
        sub_category="solvency",
        description="流动比率",
        economic_interpretation="短期偿债能力",
        lookback=0,
        data_requirement=["current_assets", "current_liabilities"],
        computation="current_assets / current_liabilities",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="quick_ratio",
        category="leverage",
        sub_category="solvency",
        description="速动比率",
        economic_interpretation="不含存货的短期偿债",
        lookback=0,
        data_requirement=["current_assets", "inventory", "current_liabilities"],
        computation="(current_assets - inventory) / current_liabilities",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="cash_ratio",
        category="leverage",
        sub_category="solvency",
        description="现金比率",
        economic_interpretation="最保守的短期偿债",
        lookback=0,
        data_requirement=["cash", "current_liabilities"],
        computation="cash / current_liabilities",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="interest_coverage",
        category="leverage",
        sub_category="coverage",
        description="利息保障倍数",
        economic_interpretation="利润覆盖利息能力",
        lookback=0,
        data_requirement=["ebit", "interest_expense"],
        computation="ebit / interest_expense",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="debt_service_coverage",
        category="leverage",
        sub_category="coverage",
        description="债务服务保障倍数",
        economic_interpretation="覆盖本金+利息",
        lookback=0,
        data_requirement=["ebitda", "principal", "interest"],
        computation="ebitda / (principal + interest)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="net_debt_to_ebitda",
        category="leverage",
        sub_category="debt_ratios",
        description="净负债/EBITDA",
        economic_interpretation="杠杆水平",
        lookback=0,
        data_requirement=["net_debt", "ebitda"],
        computation="net_debt / ebitda",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="financial_leverage",
        category="leverage",
        sub_category="leverage_factors",
        description="财务杠杆 (资产/权益)",
        economic_interpretation="杠杆倍数",
        lookback=0,
        data_requirement=["total_assets", "total_equity"],
        computation="total_assets / total_equity",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="equity_multiplier",
        category="leverage",
        sub_category="leverage_factors",
        description="权益乘数",
        economic_interpretation="股东权益撬动资产",
        lookback=0,
        data_requirement=["total_assets", "total_equity"],
        computation="1 / (1 - debt_ratio)",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="debt_growth_vs_asset_growth",
        category="leverage",
        sub_category="leverage_factors",
        description="负债增长 vs 资产增长",
        economic_interpretation="去杠杆vs加杠杆",
        lookback=0,
        data_requirement=["total_liabilities", "total_assets"],
        computation="liabilities_growth - assets_growth",
        ic_direction="positive",
    ),

    # ========== 六、现金流类 (10个) ==========

    ExtendedFinancialFactor(
        name="ocf_per_share",
        category="cash_flow",
        sub_category="ocf_metrics",
        description="每股经营现金流",
        economic_interpretation="真金白银的每股回报",
        lookback=0,
        data_requirement=["operating_cash_flow", "shares"],
        computation="operating_cash_flow / shares",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="fcf_per_share",
        category="cash_flow",
        sub_category="fcf_metrics",
        description="每股自由现金流",
        economic_interpretation="可自由支配现金",
        lookback=0,
        data_requirement=["free_cash_flow", "shares"],
        computation="free_cash_flow / shares",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="ocf_to_debt",
        category="cash_flow",
        sub_category="coverage_ratios",
        description="经营现金流/负债",
        economic_interpretation="偿债能力",
        lookback=0,
        data_requirement=["operating_cash_flow", "total_debt"],
        computation="operating_cash_flow / total_debt",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="fcf_to_debt",
        category="cash_flow",
        sub_category="coverage_ratios",
        description="自由现金流/负债",
        economic_interpretation="偿债能力",
        lookback=0,
        data_requirement=["free_cash_flow", "total_debt"],
        computation="free_cash_flow / total_debt",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="cash_conversion_ratio",
        category="cash_flow",
        sub_category="conversion_metrics",
        description="现金转换率",
        economic_interpretation="盈利质量 (现金流/利润)",
        lookback=0,
        data_requirement=["operating_cash_flow", "net_profit"],
        computation="operating_cash_flow / net_profit",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="investing_cash_flow_ratio",
        category="cash_flow",
        sub_category="cash_flow_patterns",
        description="投资支出/经营现金流",
        economic_interpretation="扩张vs收缩",
        lookback=0,
        data_requirement=["investing_cash_flow", "operating_cash_flow"],
        computation="abs(investing_cash_flow) / operating_cash_flow",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="financing_cash_flow_ratio",
        category="cash_flow",
        sub_category="cash_flow_patterns",
        description="融资现金流占比",
        economic_interpretation="外部融资依赖",
        lookback=0,
        data_requirement=["financing_cash_flow", "total_cash_flow"],
        computation="financing_cash_flow / total_cash_flow",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="capex_intensity",
        category="cash_flow",
        sub_category="capex_metrics",
        description="资本支出强度",
        economic_interpretation="维持性投资占比",
        lookback=0,
        data_requirement=["capex", "revenue"],
        computation="capex / revenue",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="ocf_growth_3y",
        category="cash_flow",
        sub_category="growth_metrics",
        description="经营现金流三年增长",
        economic_interpretation="现金持续增长",
        lookback=750,
        data_requirement=["operating_cash_flow"],
        computation="ocf_current / ocf_3y_ago - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="cash_dividend_coverage",
        category="cash_flow",
        sub_category="dividend_metrics",
        description="现金分红保障倍数",
        economic_interpretation="现金流覆盖分红",
        lookback=0,
        data_requirement=["operating_cash_flow", "cash_dividend"],
        computation="operating_cash_flow / cash_dividend",
        ic_direction="positive",
    ),

    # ========== 七、质量因子类 (13个) ==========

    ExtendedFinancialFactor(
        name="accrual_ratio",
        category="quality",
        sub_category="accrual_factors",
        description="应计利润比率",
        economic_interpretation="应计利润/总资产，盈利质量",
        lookback=0,
        data_requirement=["net_income", "operating_cash_flow", "total_assets"],
        computation="(net_income - operating_cash_flow) / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="asset_quality",
        category="quality",
        sub_category="asset_quality",
        description="资产质量 (非流动资产占比)",
        economic_interpretation="资产流动性",
        lookback=0,
        data_requirement=["non_current_assets", "total_assets"],
        computation="non_current_assets / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="receivable_to_revenue",
        category="quality",
        sub_category="receivable_quality",
        description="应收账款/营收",
        economic_interpretation="赊销比例，收入质量",
        lookback=0,
        data_requirement=["accounts_receivable", "revenue"],
        computation="accounts_receivable / revenue",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="inventory_to_revenue",
        category="quality",
        sub_category="inventory_quality",
        description="存货/营收",
        economic_interpretation="存货占比",
        lookback=0,
        data_requirement=["inventory", "revenue"],
        computation="inventory / revenue",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="big_bath_indicator",
        category="quality",
        sub_category="earnings_quality",
        description="洗大澡指标",
        economic_interpretation="一次性大幅计提",
        lookback=0,
        data_requirement=["asset_impairment", "total_assets"],
        computation="asset_impairment / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="deferred_revenue_growth",
        category="quality",
        sub_category="revenue_quality",
        description="递延收入增长率",
        economic_interpretation="预收款增长=需求好",
        lookback=0,
        data_requirement=["deferred_revenue"],
        computation="deferred_revenue / deferred_revenue_same_q_last_year - 1",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="warranty_reserve_ratio",
        category="quality",
        sub_category="contingent_liabilities",
        description="保修准备金率",
        economic_interpretation="隐性负债风险",
        lookback=0,
        data_requirement=["warranty_reserve", "revenue"],
        computation="warranty_reserve / revenue",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="tax_burden",
        category="quality",
        sub_category="tax_metrics",
        description="税负 (实际税率)",
        economic_interpretation="实际税负水平",
        lookback=0,
        data_requirement=["income_tax", "profit_before_tax"],
        computation="income_tax / profit_before_tax",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="minority_interest_ratio",
        category="quality",
        sub_category="ownership_structure",
        description="少数股东权益占比",
        economic_interpretation="子公司归母比例",
        lookback=0,
        data_requirement=["minority_interest", "total_equity"],
        computation="minority_interest / total_equity",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="goodwill_ratio",
        category="quality",
        sub_category="intangible_assets",
        description="商誉占比",
        economic_interpretation="并购溢价，减值风险",
        lookback=0,
        data_requirement=["goodwill", "total_assets"],
        computation="goodwill / total_assets",
        ic_direction="negative",
    ),
    ExtendedFinancialFactor(
        name="intangible_ratio",
        category="quality",
        sub_category="intangible_assets",
        description="无形资产占比",
        economic_interpretation="无形资产比例",
        lookback=0,
        data_requirement=["intangible_assets", "total_assets"],
        computation="intangible_assets / total_assets",
        ic_direction="conditional",
    ),
    ExtendedFinancialFactor(
        name="roe_consistency",
        category="quality",
        sub_category="roe_metrics",
        description="ROE持续性 (连续高ROE年数)",
        economic_interpretation="持续高回报能力",
        lookback=750,
        data_requirement=["roe"],
        computation="count(roe > 0.10, last_5y)",
        ic_direction="positive",
    ),
    ExtendedFinancialFactor(
        name="earnings_volatility",
        category="quality",
        sub_category="volatility_metrics",
        description="盈利波动率",
        economic_interpretation="盈利稳定性",
        lookback=750,
        data_requirement=["net_profit"],
        computation="std(net_profit_last_8q) / mean(abs(net_profit_last_8q))",
        ic_direction="negative",
    ),
]


def get_extended_financial_factors() -> list[ExtendedFinancialFactor]:
    """获取扩展财务因子列表"""
    return EXTENDED_FINANCIAL_FACTORS


def get_financial_factors_by_category(category: str) -> list[ExtendedFinancialFactor]:
    """按类别获取财务因子"""
    return [f for f in EXTENDED_FINANCIAL_FACTORS if f.category == category]


def get_financial_factor_names() -> list[str]:
    """获取所有财务因子名称"""
    return [f.name for f in EXTENDED_FINANCIAL_FACTORS]


def print_financial_factor_summary():
    """打印财务因子汇总"""
    print("=" * 80)
    print("扩展财务因子库汇总")
    print("=" * 80)
    print(f"总计: {len(EXTENDED_FINANCIAL_FACTORS)}个因子")
    print()

    categories = {}
    for f in EXTENDED_FINANCIAL_FACTORS:
        if f.category not in categories:
            categories[f.category] = []
        categories[f.category].append(f)

    for cat, factors in sorted(categories.items(), key=lambda x: -len(x[1])):
        print(f"【{cat}】{len(factors)}个")
        for f in factors[:5]:
            print(f"  - {f.name}: {f.description}")
        if len(factors) > 5:
            print(f"  ... 还有{len(factors)-5}个")
        print()


if __name__ == "__main__":
    print_financial_factor_summary()
