"""
WorldQuant Alpha因子库 - 101 Alphas的精简版

来源: Kakushadze (2016) "101 Formulaic Alphas"

WorldQuant Alpha分类:
1. Price-based (1-30)
2. Volume-based (31-54)
3. Price-Volume combined (55-76)
4. Momentum-based (77-86)
5. Mean-reversion (87-101)
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True)
class WorldQuantAlphaSpec:
    number: int
    name: str
    category: str
    formula: str
    description: str
    lookback: int
    data_requirement: list[str]


WORLDQUANT_ALPHAS = [
    # ===== Price-based Alphas (1-30) =====
    WorldQuantAlphaSpec(
        number=1,
        name="alpha_001",
        category="price",
        formula="rank(Ts_ArgMax(SignedPower(((returns < 0) ? stddev(returns, 20) : close), 2.), 15)) - 0.5",
        description="时间序列动量反转",
        lookback=20,
        data_requirement=["close", "returns"],
    ),
    WorldQuantAlphaSpec(
        number=2,
        name="alpha_002",
        category="price",
        formula="(-1 * correlation(rank(delta(log(volume), 2)), rank((close-open)/open), 6))",
        description="量价相关性",
        lookback=6,
        data_requirement=["close", "open", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=3,
        name="alpha_003",
        category="price",
        formula="(-1 * correlation(rank(open), rank(volume), 10))",
        description="开盘价与成交量",
        lookback=10,
        data_requirement=["open", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=4,
        name="alpha_004",
        category="price",
        formula="(-1 * Ts_Rank(rank(low), 9))",
        description="低价排名动量",
        lookback=9,
        data_requirement=["low"],
    ),
    WorldQuantAlphaSpec(
        number=5,
        name="alpha_005",
        category="price",
        formula="rank((open - (sum(vwap, 10) / 10))) * (-1 * abs(rank((close-vwap))))",
        description="开盘价相对VWAP",
        lookback=10,
        data_requirement=["open", "close", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=6,
        name="alpha_006",
        category="price",
        formula="(-1 * correlation(open, volume, 10))",
        description="开盘量价关系",
        lookback=10,
        data_requirement=["open", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=7,
        name="alpha_007",
        category="price",
        formula="((adv20 < volume) ? ((-1 * ts_rank(abs(delta(close, 7)), 60)) * sign(delta(close, 7))) : -1)",
        description="成交量加权动量",
        lookback=60,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=8,
        name="alpha_008",
        category="price",
        formula="(-1 * rank(((sum(open, 5) * sum(returns, 5)) - delay((sum(open, 5) * sum(returns, 5)), 10))))",
        description="开盘收益动量",
        lookback=10,
        data_requirement=["open", "returns"],
    ),
    WorldQuantAlphaSpec(
        number=9,
        name="alpha_009",
        category="price",
        formula="((0 < ts_min(delta(close, 1), 5)) ? delta(close, 1) : ((ts_max(delta(close, 1), 5) < 0) ? delta(close, 1) : -delta(close,1)))",
        description="条件价格变化",
        lookback=5,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=10,
        name="alpha_010",
        category="price",
        formula="rank(((0 < ts_min(delta(close, 1), 4)) ? delta(close, 1) : ((ts_max(delta(close, 1), 4) < 0) ? delta(close, 1) : -delta(close, 1))))",
        description="短期价格动量",
        lookback=4,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=11,
        name="alpha_011",
        category="price",
        formula="((rank(ts_max((vwap - close), 3)) + rank(ts_min((vwap - close), 3))) * rank(delta(volume, 3)))",
        description="VWAP偏离动量",
        lookback=3,
        data_requirement=["vwap", "close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=12,
        name="alpha_012",
        category="price",
        formula="sign(delta(volume, 1)) * (-1 * delta(close, 1))",
        description="量价背离",
        lookback=1,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=13,
        name="alpha_013",
        category="price",
        formula="(-1 * rank(covariance(rank(close), rank(volume), 5)))",
        description="价格成交量协方差",
        lookback=5,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=14,
        name="alpha_014",
        category="price",
        formula="((-1 * rank(delta(returns, 3))) * correlation(open, volume, 10))",
        description="收益变化量价相关",
        lookback=10,
        data_requirement=["open", "volume", "returns"],
    ),
    WorldQuantAlphaSpec(
        number=15,
        name="alpha_015",
        category="price",
        formula="((rank(ts_max((vwap - close), 3)) - rank(ts_min((vwap - close), 3))) * rank(delta(volume, 3)))",
        description="VWAP范围动量",
        lookback=3,
        data_requirement=["vwap", "close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=16,
        name="alpha_016",
        category="price",
        formula="(-1 * correlation(rank(high), rank(volume), 5))",
        description="高价成交量关系",
        lookback=5,
        data_requirement=["high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=17,
        name="alpha_017",
        category="price",
        formula="((( -1 * rank(ts_rank(close, 10))) * rank(delta(delta(close, 1), 1))) *rank(ts_rank((volume / adv20), 5)))",
        description="价格动量组合",
        lookback=10,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=18,
        name="alpha_018",
        category="price",
        formula="(-1 * rank(((stddev(abs((close - open)), 5) + (close - open)) + correlation(close, open, 10))))",
        description="日内波动率",
        lookback=10,
        data_requirement=["close", "open"],
    ),
    WorldQuantAlphaSpec(
        number=19,
        name="alpha_019",
        category="price",
        formula="(((((2.21 * rank(correlation((close * 0.9), adv20, 10))) + (0.7 * rank((open - close)))) + (0.73 * rank(ts_rank((-delta(close, 1)), 15)))) + (0.6 * rank((((sum(close, 100) / 100) - close) * (open - close)))))",
        description="综合价格信号",
        lookback=100,
        data_requirement=["close", "open", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=20,
        name="alpha_020",
        category="price",
        formula="(-1 * (rank((open - delay(high, 1))) * rank((open - delay(close, 1))) * rank((open - delay(low, 1)))))",
        description="开盘价位置",
        lookback=1,
        data_requirement=["open", "high", "low", "close"],
    ),
    WorldQuantAlphaSpec(
        number=21,
        name="alpha_021",
        category="price",
        formula="((((sum(close, 8) / 8) + stddev(close, 8)) < (sum(close, 2) / 2)) ? (-1 * 1) : (((sum(close, 2) / 2) < ((sum(close, 8) / 8) - stddev(close, 8))) ? 1 : ((1 < (volume / adv20)) || ((volume / adv20) == 1)) ? 1 : -1))",
        description="均值回归+成交量",
        lookback=8,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=22,
        name="alpha_022",
        category="price",
        formula="(-1 * (delta(correlation(high, volume, 5), 5) * rank(stddev(close, 20))))",
        description="波动率变化",
        lookback=20,
        data_requirement=["high", "close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=23,
        name="alpha_023",
        category="price",
        formula="(((sum(high, 20) / 20) < high) ? (-1 * delta(high, 2)) : 0)",
        description="新高信号",
        lookback=20,
        data_requirement=["high"],
    ),
    WorldQuantAlphaSpec(
        number=24,
        name="alpha_024",
        category="price",
        formula="(((((-1 * delta(ts_min(close, 5), 5)) * rank(((stddev((close / open), 20)) ** 2))) * ts_rank(((volume / adv20) * ((close - open) / open)), 5)) - rank(ts_argmax(((close * 0.35) + (vwap * 0.65)), 3))))",
        description="综合均值回归",
        lookback=20,
        data_requirement=["close", "open", "volume", "vwap", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=25,
        name="alpha_025",
        category="price",
        formula="(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 5)), 5))",
        description="成交量VWAP相关",
        lookback=5,
        data_requirement=["volume", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=26,
        name="alpha_026",
        category="price",
        formula="(((0.25 < (((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10))) ? (-1 * 1) : (((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < 0) ? 1 : ((-1 * 1) * (close - delay(close, 1))))))",
        description="价格加速度",
        lookback=20,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=27,
        name="alpha_027",
        category="price",
        formula="(-1 * delta((((close - low) - (high - close)) / (close - low)), 9))",
        description="价格位置变化",
        lookback=9,
        data_requirement=["close", "high", "low"],
    ),
    WorldQuantAlphaSpec(
        number=28,
        name="alpha_028",
        category="price",
        formula="((-1 * ((low - close) * (open**5))) / ((low - high) * (close**5)))",
        description="价格形态",
        lookback=1,
        data_requirement=["close", "open", "high", "low"],
    ),
    WorldQuantAlphaSpec(
        number=29,
        name="alpha_029",
        category="price",
        formula="(-1 * correlation(rank(((close - ts_min(low, 12)) / (ts_max(high, 12) - ts_min(low, 12)))), rank(volume), 6))",
        description="价格位置量相关",
        lookback=12,
        data_requirement=["close", "low", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=30,
        name="alpha_030",
        category="price",
        formula="((0 < (20 * close)) ? 0 : ((-1 * ts_rank((abs(delta(close, 4)) / (vwap - close)), 15)) * (delta(close, 4) < 0)))",
        description="价格变动信号",
        lookback=15,
        data_requirement=["close", "vwap"],
    ),
    
    # ===== Volume-based Alphas (31-54) =====
    WorldQuantAlphaSpec(
        number=31,
        name="alpha_031",
        category="volume",
        formula="((ts_rank(volume, 32) * (1 - ts_rank(((close + high) - low), 16))) * (1 - ts_rank(returns, 32)))",
        description="量排名",
        lookback=32,
        data_requirement=["close", "high", "low", "volume", "returns"],
    ),
    WorldQuantAlphaSpec(
        number=32,
        name="alpha_032",
        category="volume",
        formula="(((0.5 < rank((sum(returns, 10) / sum(sum(returns, 2), 3)))) * (-1 * 1))",
        description="累积收益动量",
        lookback=10,
        data_requirement=["returns"],
    ),
    WorldQuantAlphaSpec(
        number=33,
        name="alpha_033",
        category="volume",
        formula="((-1 * rank((stddev(high, 10) + correlation(high, volume, 10)))) + (low * 0.9)",
        description="高价波动",
        lookback=10,
        data_requirement=["high", "low", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=34,
        name="alpha_034",
        category="volume",
        formula="(-1 * Ts_Rank(correlation(rank(high), rank(volume), 3), 3))",
        description="高价量相关",
        lookback=3,
        data_requirement=["high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=35,
        name="alpha_035",
        category="volume",
        formula="((-1 * ((delay(close, 20) - delay(open, 20)) * rank(correlation(adv20, low, 5))))",
        description="价格缺口",
        lookback=20,
        data_requirement=["close", "open", "adv20", "low"],
    ),
    WorldQuantAlphaSpec(
        number=36,
        name="alpha_036",
        category="volume",
        formula="((0.5 < rank((sum((close > open), 10) / 10.0))) * (-1 * 1))",
        description="上涨天数占比",
        lookback=10,
        data_requirement=["close", "open"],
    ),
    WorldQuantAlphaSpec(
        number=37,
        name="alpha_037",
        category="volume",
        formula="((-1 * volume / adv20) * ((close - open) / correlation(close, open, 10)))",
        description="成交量调整收益",
        lookback=10,
        data_requirement=["close", "open", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=38,
        name="alpha_038",
        category="volume",
        formula="((rank((1 / close)) * volume) / adv20) * ((high * rank((high - close))) / (sum(high, 5) / 5))",
        description="成交量加权价格",
        lookback=5,
        data_requirement=["close", "high", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=39,
        name="alpha_039",
        category="volume",
        formula="((-1 * rank((sum(delay(close, 5), 20) / 20.0)) * correlation(close, volume, 2)) * 0.5",
        description="滞后价格相关",
        lookback=20,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=40,
        name="alpha_040",
        category="volume",
        formula="((-1 * delta(correlation(((high * 0.9) + (close * 0.1)), adv20, 10), 7)) * rank(stddev(close, 20)))",
        description="加权价格相关",
        lookback=20,
        data_requirement=["close", "high", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=41,
        name="alpha_041",
        category="volume",
        formula="(((sum(close, 7) / 7) - close) + (20 * correlation((close - vwap), delay(close, 5), 230)))",
        description="VWAP偏离",
        lookback=230,
        data_requirement=["close", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=42,
        name="alpha_042",
        category="volume",
        formula="(-1 * rank(((open - delay(close, 1)) * (open - delay(low, 1)))))",
        description="开盘形态",
        lookback=1,
        data_requirement=["open", "close", "low"],
    ),
    WorldQuantAlphaSpec(
        number=43,
        name="alpha_043",
        category="volume",
        formula="((volume / adv20) * ((close - low) - (high - close))) / (high - low)",
        description="日内成交分布",
        lookback=1,
        data_requirement=["close", "high", "low", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=44,
        name="alpha_044",
        category="volume",
        formula="((-1 * ts_rank(correlation(((high * 0.9) + (close * 0.1)), volume, 7), 3)) * ts_rank(delta(delta(close, 1), 1), 3))",
        description="加权价格量相关",
        lookback=7,
        data_requirement=["close", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=45,
        name="alpha_045",
        category="volume",
        formula="(-1 * rank(correlation(adv20, low, 5))) * ((close - delay(close, 3)) / delay(close, 3))",
        description="成交量价格动量",
        lookback=5,
        data_requirement=["close", "adv20", "low"],
    ),
    WorldQuantAlphaSpec(
        number=46,
        name="alpha_046",
        category="volume",
        formula="((-1 * ((close - delay(close, 3)) / delay(close, 3)) * ts_rank(volume, 10)))",
        description="收益成交量",
        lookback=10,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=47,
        name="alpha_047",
        category="volume",
        formula="((-1 * correlation(rank(open), rank(volume), 10)) * rank(((close - open) / open)))",
        description="开盘价成交量相关",
        lookback=10,
        data_requirement=["open", "close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=48,
        name="alpha_048",
        category="volume",
        formula="((-1 * ts_rank((((high + low) / 2) - close), 8)) * ts_rank(correlation(((high + low) / 2), adv20, 8), 7))",
        description="价格中心量相关",
        lookback=8,
        data_requirement=["close", "high", "low", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=49,
        name="alpha_049",
        category="volume",
        formula="((-1 * ts_rank(correlation(close, volume, 7), 7)) * ts_rank(delta(((close * 0.8) + (vwap * 0.2)), 1), 8))",
        description="收盘量相关动量",
        lookback=8,
        data_requirement=["close", "volume", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=50,
        name="alpha_050",
        category="volume",
        formula="((((-1 * ts_min(low, 5)) + delay(close, 5)) * rank(((sum(returns, 240) - sum(returns, 20)) / 220.0))) * ts_rank((volume / adv20), 5))",
        description="价格突破",
        lookback=240,
        data_requirement=["close", "low", "returns", "volume", "adv20"],
    ),
    
    # ===== Price-Volume Combined (55-76) =====
    WorldQuantAlphaSpec(
        number=55,
        name="alpha_055",
        category="price_volume",
        formula="(-1 * rank(delta((((close * 0.8) + (vwap * 0.2)) / (vwap - delay(((close * 0.8) + (vwap * 0.2)), 1))), 1)) * ts_rank((volume / adv20), 15))",
        description="VWAP动量",
        lookback=15,
        data_requirement=["close", "vwap", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=56,
        name="alpha_056",
        category="price_volume",
        formula="(-1 * correlation(correlation(((close * 0.8) + (vwap * 0.2)), volume, 4), ((close * 0.8) + (vwap * 0.2)), 4))",
        description="VWAP量相关",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=57,
        name="alpha_057",
        category="price_volume",
        formula="((0.5 - rank(delta((((close * 0.8) + (vwap * 0.2)), 1))) * ts_rank((volume / adv20), 16))",
        description="VWAP变化成交量",
        lookback=16,
        data_requirement=["close", "vwap", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=58,
        name="alpha_058",
        category="price_volume",
        formula="(0.3 - rank(correlation(((close * 0.8) + (vwap * 0.2)), volume, 4)))",
        description="VWAP成交量相关",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=59,
        name="alpha_059",
        category="price_volume",
        formula="((0.3 - rank(delta(((close * 0.8) + (vwap * 0.2)), 1))) * ts_rank((volume / adv20), 15))",
        description="VWAP变化量排名",
        lookback=15,
        data_requirement=["close", "vwap", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=60,
        name="alpha_060",
        category="price_volume",
        formula="(-1 * ts_rank(correlation((vwap - close), delta(adv20, 3), 5), 4))",
        description="VWAP-CLOSE差量相关",
        lookback=5,
        data_requirement=["close", "vwap", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=61,
        name="alpha_061",
        category="price_volume",
        formula="((-1 * delta((((high * 0.9) + (close * 0.1)) - vwap) / (vwap - delay(vwap, 1)), 1)) * ts_rank((volume / adv20), 5))",
        description="VWAP偏离动量",
        lookback=5,
        data_requirement=["close", "high", "vwap", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=62,
        name="alpha_062",
        category="price_volume",
        formula="(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 5)), 5))",
        description="成交量VWAP相关最大值",
        lookback=5,
        data_requirement=["volume", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=63,
        name="alpha_063",
        category="price_volume",
        formula="((-1 * rank(delta(((close * 0.8) + (vwap * 0.2)), 1))) * ts_rank(correlation(((close * 0.8) + (vwap * 0.2)), volume, 5), 3))",
        description="VWAP变化量相关",
        lookback=5,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=64,
        name="alpha_064",
        category="price_volume",
        formula="(-1 * rank(correlation(((close * 0.8) + (vwap * 0.2)), adv20, 4)))",
        description="VWAP量平均相关",
        lookback=4,
        data_requirement=["close", "vwap", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=65,
        name="alpha_065",
        category="price_volume",
        formula="((-1 * rank(delta(((close * 0.8) + (vwap * 0.2)), 1))) * (rank(correlation(adv20, volume, 4)) + rank(delta(vwap, 1))))",
        description="综合VWAP信号",
        lookback=4,
        data_requirement=["close", "vwap", "adv20", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=66,
        name="alpha_066",
        category="price_volume",
        formula="(-1 * ts_rank(correlation(rank(vwap), rank(volume), 4), 3)) * ts_rank(delta(close, 1), 4))",
        description="VWAP量排名动量",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=67,
        name="alpha_067",
        category="price_volume",
        formula="(-1 * ts_rank(correlation(rank(open), rank(volume), 4), 3)) * ts_rank(delta(close, 1), 4))",
        description="开盘量相关动量",
        lookback=4,
        data_requirement=["open", "close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=68,
        name="alpha_068",
        category="price_volume",
        formula="((-1 * rank(correlation(((high * 0.9) + (close * 0.1)), volume, 4))) * ts_rank(delta(delta(close, 1), 1), 2))",
        description="价格量相关动量",
        lookback=4,
        data_requirement=["close", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=69,
        name="alpha_069",
        category="price_volume",
        formula="(-1 * (rank(correlation(close, volume, 4)) * ts_rank(close, 2)) * ts_rank(correlation(vwap, adv20, 6), 3))",
        description="多因子组合",
        lookback=6,
        data_requirement=["close", "volume", "vwap", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=70,
        name="alpha_070",
        category="price_volume",
        formula="(-1 * ((0.2 < ((close - delay(close, 1)) / delay(close, 1))) * (-1 * (close - delay(close, 1)))))",
        description="收益动量",
        lookback=1,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=71,
        name="alpha_071",
        category="price_volume",
        formula="((-1 * (close - delay(close, 1))) * rank((open / close)))",
        description="日间收益",
        lookback=1,
        data_requirement=["close", "open"],
    ),
    WorldQuantAlphaSpec(
        number=72,
        name="alpha_072",
        category="price_volume",
        formula="(-1 * ((close - delay(close, 1)) * ((close - delay(close, 1)) / ((close + delay(close, 1)) / 2))))",
        description="收益率方差",
        lookback=1,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=73,
        name="alpha_073",
        category="price_volume",
        formula="(-1 * delta((((close - delay(close, 1)) / delay(close, 1)) - ((close - delay(close, 5)) / delay(close, 5))), 3))",
        description="收益变化率",
        lookback=5,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=74,
        name="alpha_074",
        category="price_volume",
        formula="((-1 * ts_rank(ts_rank(correlation(close, volume, 5), 3), 3)) * ts_rank(delta(close, 1), 4))",
        description="量价相关排名",
        lookback=5,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=75,
        name="alpha_075",
        category="price_volume",
        formula="((-1 * rank(correlation(close, volume, 4))) * ts_rank(delta(close, 1), 3))",
        description="量相关动量",
        lookback=4,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=76,
        name="alpha_076",
        category="price_volume",
        formula="(-1 * ts_rank(correlation(delta((close - delay(close, 1)), 1), delta(close - delay(close, 1), 1), 3), 3))",
        description="收益变化相关",
        lookback=3,
        data_requirement=["close"],
    ),
    
    # ===== Momentum-based (77-86) =====
    WorldQuantAlphaSpec(
        number=77,
        name="alpha_077",
        category="momentum",
        formula="(-1 * rank(correlation(delta(close, 1), delta(close, 5), 3)))",
        description="收益相关性",
        lookback=5,
        data_requirement=["close"],
    ),
    WorldQuantAlphaSpec(
        number=78,
        name="alpha_078",
        category="momentum",
        formula="(-1 * ts_rank(delta(close, 1), 4) * ts_rank(delta(close - vwap, 1), 4))",
        description="价格VWAP动量",
        lookback=4,
        data_requirement=["close", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=79,
        name="alpha_079",
        category="momentum",
        formula="(-1 * delta(((close - delay(close, 3)) / delay(close, 3)), 3) * correlation(((close * 0.8) + (vwap * 0.2)), volume, 5))",
        description="收益VWAP量相关",
        lookback=5,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=80,
        name="alpha_080",
        category="momentum",
        formula="((rank(delta((vwap * 0.7) + (close * 0.3), 4)) * (-1 * ts_rank(correlation(vwap, volume, 5), 3)))",
        description="VWAP动量成交量",
        lookback=5,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=81,
        name="alpha_081",
        category="momentum",
        formula="(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 4)), 4)) * ts_rank(delta(close, 1), 4)",
        description="成交量VWAP动量",
        lookback=4,
        data_requirement=["close", "volume", "vwap"],
    ),
    WorldQuantAlphaSpec(
        number=82,
        name="alpha_082",
        category="momentum",
        formula="(-1 * rank(correlation(vwap, volume, 4))) * ts_rank(delta(close, 1), 4)",
        description="VWAP量相关动量",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=83,
        name="alpha_083",
        category="momentum",
        formula="((0.3 - rank(delta(close, 1))) * ts_rank((volume / adv20), 3))",
        description="价格变化成交量",
        lookback=3,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=84,
        name="alpha_084",
        category="momentum",
        formula="(-1 * rank(correlation(rank(((close * 0.8) + (vwap * 0.2))), rank(volume), 4))) * ts_rank(delta(close, 1), 4)",
        description="加权价格量动量",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=85,
        name="alpha_085",
        category="momentum",
        formula="(-1 * ((0.3 < rank((close - delay(close, 1)))) * ts_rank((volume / adv20), 3)))",
        description="正收益成交量",
        lookback=3,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=86,
        name="alpha_086",
        category="momentum",
        formula="((-1 * ts_rank(correlation(close, volume, 4), 3)) * ts_rank(correlation(delta(close, 1), delta(close, 1), 3), 3))",
        description="量价相关收益相关",
        lookback=4,
        data_requirement=["close", "volume"],
    ),
    
    # ===== Mean-reversion (87-101) =====
    WorldQuantAlphaSpec(
        number=87,
        name="alpha_087",
        category="mean_reversion",
        formula="((-1 * delta(correlation(close, volume, 3), 1)) * ts_rank(correlation(rank(close), rank(volume), 3), 3))",
        description="量价相关变化",
        lookback=3,
        data_requirement=["close", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=88,
        name="alpha_088",
        category="mean_reversion",
        formula="(-1 * rank(delta(correlation(((high * 0.8) + (close * 0.2)), volume, 3), 1))) * ts_rank(volume, 3)",
        description="高价量相关变化",
        lookback=3,
        data_requirement=["close", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=89,
        name="alpha_089",
        category="mean_reversion",
        formula="((-1 * delta(correlation(rank(((close * 0.8) + (vwap * 0.2))), rank(volume), 3), 1)) * ts_rank(correlation(((close * 0.8) + (vwap * 0.2)), volume, 3), 3))",
        description="VWAP量相关变化",
        lookback=3,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=90,
        name="alpha_090",
        category="mean_reversion",
        formula="(-1 * rank(delta(((close - vwap) / (vwap - delay(vwap, 1))), 1)) * ts_rank(correlation(vwap, adv20, 5), 3))",
        description="VWAP偏离均值回归",
        lookback=5,
        data_requirement=["close", "vwap", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=91,
        name="alpha_091",
        category="mean_reversion",
        formula="(-1 * delta(correlation(rank(((high * 0.8) + (vwap * 0.2))), rank(volume), 3), 2))",
        description="高价VWAP量相关",
        lookback=3,
        data_requirement=["high", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=92,
        name="alpha_092",
        category="mean_reversion",
        formula="((-1 * rank(correlation(((high * 0.8) + (close * 0.2)), rank(volume), 4)))) - ts_rank(delta(close, 1), 4)",
        description="加权价格量相关",
        lookback=4,
        data_requirement=["close", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=93,
        name="alpha_093",
        category="mean_reversion",
        formula="(-1 * rank(delta(correlation(((high * 0.8) + (close * 0.2)), rank(volume), 3), 1))) * ts_rank(delta(((high * 0.8) + (close * 0.2)), 1), 3)",
        description="加权价格变化量相关",
        lookback=3,
        data_requirement=["close", "high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=94,
        name="alpha_094",
        category="mean_reversion",
        formula="((-1 * ts_rank(correlation(rank(high), rank(volume), 3), 3)) * ts_rank(delta(high, 1), 3))",
        description="高价量相关动量",
        lookback=3,
        data_requirement=["high", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=95,
        name="alpha_095",
        category="mean_reversion",
        formula="(-1 * rank(correlation(rank(low), rank(volume), 3))) * ts_rank(correlation(((low * 0.8) + (vwap * 0.2)), volume, 3), 3))",
        description="低价量相关",
        lookback=3,
        data_requirement=["low", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=96,
        name="alpha_096",
        category="mean_reversion",
        formula="(-1 * rank(correlation(rank(((close * 0.8) + (vwap * 0.2))), rank(volume), 4))) * ts_rank(((close - delay(close, 1)) / delay(close, 1)), 3))",
        description="VWAP量相关收益",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=97,
        name="alpha_097",
        category="mean_reversion",
        formula="(-1 * ts_rank(correlation(rank(volume), rank(((close * 0.8) + (vwap * 0.2))), 4), 3)) * ts_rank(delta(close, 1), 3)",
        description="成交量VWAP相关",
        lookback=4,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=98,
        name="alpha_098",
        category="mean_reversion",
        formula="(-1 * ts_rank(correlation(((close * 0.8) + (vwap * 0.2)), rank(volume), 3), 3)) * ts_rank(correlation(ts_min(((close * 0.8) + (vwap * 0.2)), 3), ts_max(((close * 0.8) + (vwap * 0.2)), 3), 3), 3))",
        description="VWAP极值相关",
        lookback=3,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=99,
        name="alpha_099",
        category="mean_reversion",
        formula="((rank((close / delay(close, 1) - 1)) * ts_rank((volume / adv20), 3)) * (-1 * ts_rank(((close - delay(close, 5)) / delay(close, 5)), 3)))",
        description="短期收益成交量",
        lookback=5,
        data_requirement=["close", "volume", "adv20"],
    ),
    WorldQuantAlphaSpec(
        number=100,
        name="alpha_100",
        category="mean_reversion",
        formula="((-1 * ts_rank(delta((((close * 0.8) + (vwap * 0.2)) - delay(((close * 0.8) + (vwap * 0.2)), 1)), 3)) * ts_rank(correlation(((close * 0.8) + (vwap * 0.2)), volume, 3), 3))",
        description="VWAP动量成交量",
        lookback=3,
        data_requirement=["close", "vwap", "volume"],
    ),
    WorldQuantAlphaSpec(
        number=101,
        name="alpha_101",
        category="mean_reversion",
        formula="((-1 * ts_rank(delta((((close * 0.8) + (vwap * 0.2)) - delay(((close * 0.8) + (vwap * 0.2)), 1)), 3)) * ts_rank(correlation(((close * 0.8) + (vwap * 0.2)), volume, 3), 3))",
        description="VWAP动量成交量(简化)",
        lookback=3,
        data_requirement=["close", "vwap", "volume"],
    ),
]


def get_wq_alpha_names() -> list[str]:
    """获取所有WorldQuant Alpha名称"""
    return [a.name for a in WORLDQUANT_ALPHAS]


def get_wq_alphas_by_category(category: str) -> list[WorldQuantAlphaSpec]:
    """按类别获取Alpha"""
    return [a for a in WORLDQUANT_ALPHAS if a.category == category]


def print_wq_alpha_summary():
    """打印WorldQuant Alpha库汇总"""
    print("=" * 100)
    print("WorldQuant Alpha因子库汇总")
    print("=" * 100)
    
    categories = {}
    for a in WORLDQUANT_ALPHAS:
        if a.category not in categories:
            categories[a.category] = []
        categories[a.category].append(a)
    
    for cat, alphas in sorted(categories.items()):
        print(f"\n【{cat.upper()}】{len(alphas)}个因子")
        for a in alphas[:5]:  # 只显示前5个
            print(f"  Alpha_{a.number:03d}: {a.description}")
        if len(alphas) > 5:
            print(f"  ... 还有{len(alphas)-5}个")
    
    print(f"\n总计: {len(WORLDQUANT_ALPHAS)}个WorldQuant Alpha")


if __name__ == "__main__":
    print_wq_alpha_summary()
